baseURL: '/'

languageCode: en
DefaultContentLanguage: en

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: false

paginate: 100

summaryLength: 1

enableInlineShortcodes: true

theme: "github.com/nunocoracao/blowfish/v2"

outputs:
  home: ["HTML", "RSS", "JSON"]

sitemap:
  changefreq: "always"
  filename: "sitemap.xml"
  priority: 0.5

related:
  threshold: 0
  toLower: false
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 100
    - name: "series"
      weight: 50
    - name: "authors"
      weight: 20
    - name: "date"
      weight: 10
    - applyFilter: false
      name: 'fragmentrefs'
      type: 'fragments'
      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

server:
  headers:
    - for: /**
      values:
        Referrer-Policy: strict-origin-when-cross-origin

module:
  hugoVersion:
    extended: true
    min: "0.111.3"
  imports:
    - path: github.com/nunocoracao/blowfish/v2
