languageCode: "en"
languageName: "English"
weight: 1
title: "The Procedural Blog"

params:
  displayName: "English"
  isoCode: "en"
  rtl: false
  dateFormat: "2 January 2006"
  description: "A blog concerning procedural generation."
