main:
  - name: Blog
    pageRef: "posts"
    weight: 10
  - name: About
    pageRef: "about"
    weight: 20
  - name: Contact
    pageRef: "contact"
    weight: 30
  - name: GitHub
    pre: github
    url: https://github.com/Infinity-Generation/infinity-generation.github.io
    weight: 40
footer:
  - name: Blog
    pageRef: "posts"
    weight: 10
  - name: About
    pageRef: "about"
    weight: 20
  - name: Contact
    pageRef: "contact"
    weight: 30
  - name: GitHub
    pre: github
    url: https://github.com/Infinity-Generation/infinity-generation.github.io
    weight: 40