colorScheme: "blowfish"
copyright: "© { year } The Procedural Blog"
enableSearch: true
enableCodeCopy: true
highlightCurrentMenuArea: true
smartTOC: true
smartTOCHideUnfocusedChildren: false
header:
  layout: "fixed-fill"
homepage:
  layout: "profile"
  showRecent: true
  showRecentItems: 20
  showMoreLink: true
  cardView: true
footer:
  showScrollToTop: true
article:
  showZenMode: false
  showAuthors: true
  showBreadcrumbs: true
  showPagination: true
  invertPagination: true
  showWordCount: false
list:
  showSummary: true
  showCards: true
  cardView: false
  showTableOfContents: true
taxonomy:
  showTermCount: true
  showHero: true
  heroStyle: "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs: false
  showViews: true
  showLikes: true
  showTableOfContents: true
  cardView: false
