colorScheme: "blowfish"
enableSearch: true
enableCodeCopy: true
highlightCurrentMenuArea: true
smartTOC: true
smartTOCHideUnfocusedChildren: false
header:
  layout: "fixed-fill"
homepage:
  layout: "profile"
  showRecent: true
  showMoreLink: true
  cardView: true
article:
  showZenMode: true
  showAuthors: true
list:
  showSummary: true
  showCards: true
  cardView: true
