# config.yaml
baseURL: "/"
title: The Infinity Procedural Series
theme: simple-dark
languageCode: en
defaultContentLanguage: en

# Params
params:
    mainSections: ["post"]
    intro: true
    headline: "The procedural generation blog"
    description: "A blog concerning procedural generation"
    github: "https://github.com/Infinity-Generation/infinity-generation.github.io"
    twitter: "https://twitter.com/InfinityGenInc"
    email: "nolan@infinitygeneration.com"
    opengraph: true
    shareTwitter: true
    dateFormat: "Mon, Jan 2, 2006"

# Permalinks
permalinks:
    post: "/:filename/"

# How many posts to show on the home page; the default is 10 and the maximum is 100.
paginate: 20

# Markup configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
